"""add_public_repository_fields

Revision ID: 08ba377df936
Revises: 43a8a16df2c8
Create Date: 2026-09-29 19:04:53.687894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ba377df936'
down_revision: Union[str, Sequence[str], None] = '43a8a16df2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('github_owner', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('monitoring_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'monitoring_enabled')
    op.drop_column('repositories', 'github_updated_at')
    op.drop_column('repositories', 'github_created_at')
    op.drop_column('repositories', 'is_public')
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'github_owner')
    op.drop_column('repositories', 'provider')
    # ### end Alembic commands ###
