"""Add commit metadata

Revision ID: 43a8a16df2c8
Revises: fe60afd336cc
Create Date: 2026-09-28 20:57:38.073599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a8a16df2c8'
down_revision: Union[str, Sequence[str], None] = 'fe60afd336cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('author_name', sa.String(), nullable=True))
    op.add_column('commits', sa.Column('author_email', sa.String(), nullable=True))
    op.add_column('commits', sa.Column('committed_at', sa.DateTime(), nullable=True))
    op.add_column('commits', sa.Column('parent_shas', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'parent_shas')
    op.drop_column('commits', 'committed_at')
    op.drop_column('commits', 'author_email')
    op.drop_column('commits', 'author_name')
    # ### end Alembic commands ###
