"""add monitoring status

Revision ID: 81757b410cdd
Revises: 08ba377df936
Create Date: 2026-09-29 20:18:03.090110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81757b410cdd'
down_revision: Union[str, Sequence[str], None] = '08ba377df936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('monitoring_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'monitoring_status')
    # ### end Alembic commands ###
